spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    
forum:
  roles:
    student: Student
    professor: Professor